Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Security/Eval:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false